/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package View;

import View.Person.FrmGetAllPerson;
import View.Person.FrmInsertPerson;
import View.Provider.FrmGetAllProvider;
import View.Provider.FrmInsertProvider;

/**
 *
 * @author KAAF0
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();
        menuProvider = new javax.swing.JMenu();
        menuItemProviderInsert = new javax.swing.JMenuItem();
        menuItemProviderGetAll = new javax.swing.JMenuItem();
        menuPerson = new javax.swing.JMenu();
        menuItemPersonInsert = new javax.swing.JMenuItem();
        menuItemPersonGetAll = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de directorio telefónico");

        menuFile.setText("Archivo");

        menuItemExit.setText("Salir");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        menuBar.add(menuFile);

        menuProvider.setText("Proveedor");

        menuItemProviderInsert.setMnemonic('t');
        menuItemProviderInsert.setText("Registrar datos");
        menuItemProviderInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProviderInsertActionPerformed(evt);
            }
        });
        menuProvider.add(menuItemProviderInsert);

        menuItemProviderGetAll.setMnemonic('t');
        menuItemProviderGetAll.setText("Ver datos");
        menuItemProviderGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProviderGetAllActionPerformed(evt);
            }
        });
        menuProvider.add(menuItemProviderGetAll);

        menuBar.add(menuProvider);

        menuPerson.setText("Persona");

        menuItemPersonInsert.setText("Registrar datos");
        menuItemPersonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPersonInsertActionPerformed(evt);
            }
        });
        menuPerson.add(menuItemPersonInsert);

        menuItemPersonGetAll.setText("Ver datos");
        menuItemPersonGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPersonGetAllActionPerformed(evt);
            }
        });
        menuPerson.add(menuItemPersonGetAll);

        menuBar.add(menuPerson);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemProviderInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProviderInsertActionPerformed
        FrmInsertProvider frmInsertProvider = new FrmInsertProvider();
        
        this.desktopPane.add(frmInsertProvider);
        
        frmInsertProvider.setVisible(true);
    }//GEN-LAST:event_menuItemProviderInsertActionPerformed

    private void menuItemProviderGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProviderGetAllActionPerformed
        FrmGetAllProvider frmGetAllProvider = new FrmGetAllProvider();
        
        this.desktopPane.add(frmGetAllProvider);
        
        frmGetAllProvider.setVisible(true);
    }//GEN-LAST:event_menuItemProviderGetAllActionPerformed

    private void menuItemPersonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPersonInsertActionPerformed
        FrmInsertPerson frmInsertPerson = new FrmInsertPerson();
        
        this.desktopPane.add(frmInsertPerson);
        
        frmInsertPerson.setVisible(true);
    }//GEN-LAST:event_menuItemPersonInsertActionPerformed

    private void menuItemPersonGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPersonGetAllActionPerformed
        FrmGetAllPerson frmGetAllPerson = new FrmGetAllPerson();
        
        this.desktopPane.add(frmGetAllPerson);
        
        frmGetAllPerson.setVisible(true);
    }//GEN-LAST:event_menuItemPersonGetAllActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemPersonGetAll;
    private javax.swing.JMenuItem menuItemPersonInsert;
    private javax.swing.JMenuItem menuItemProviderGetAll;
    private javax.swing.JMenuItem menuItemProviderInsert;
    private javax.swing.JMenu menuPerson;
    private javax.swing.JMenu menuProvider;
    // End of variables declaration//GEN-END:variables

}
